# Generated by Django 3.1.4 on 2020-12-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('author', 'description')},
            },
        ),
        migrations.CreateModel(
            name='SharedNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_views', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('shared_date', models.DateTimeField(blank=True, null=True)),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharedUser', to='accounts.user')),
                ('shared_news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharedNews', to='news.news')),
            ],
        ),
    ]
