# Generated by Django 3.1.4 on 2020-12-29 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharednews',
            name='shared_by',
        ),
        migrations.RemoveField(
            model_name='sharednews',
            name='shared_news',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='SharedNews',
        ),
    ]
