# Generated by Django 3.1.4 on 2020-12-30 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('news', '0002_auto_20201230_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField()),
                ('shared_views', models.TextField(blank=True, default='', null=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('shared_date', models.DateTimeField(blank=True, null=True)),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharedUser', to='accounts.user')),
            ],
        ),
    ]
