# Generated by Django 3.1.4 on 2020-12-30 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_sharednews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharednews',
            name='slug',
        ),
    ]
