# Generated by Django 3.1.4 on 2020-12-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_sharednews_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharednews',
            name='slug',
            field=models.SlugField(allow_unicode=True, null=True, unique=True),
        ),
    ]
