# Generated by Django 3.1.4 on 2020-12-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_sharednews_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharednews',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sharednews',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sharednews',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
