# Generated by Django 3.1.4 on 2020-12-31 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20201231_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharednews',
            name='slug',
        ),
    ]
