# Generated by Django 3.1.4 on 2021-01-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_sharednews_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharednews',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sharednews',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
